export default function Home(){return <main>
<header className="top"><a className="brand" href="#top"><span className="logo">M</span><span><strong>LE MAMBO</strong><small>ORIGINAL NIGHT BAR</small></span></a><nav><a href="#experience">Le Mambo</a><a href="#events">Soirées</a><a href="#infos">Infos</a></nav><a className="cta" href="#events">Ce week-end →</a></header>
<section className="hero" id="top"><div className="heroCopy"><div className="eyebrow">CONDÉ-EN-NORMANDIE · BAR DE NUIT</div><h1>La nuit<br/><em>commence ici.</em></h1><p>Un vrai bar de nuit : cocktails, lumières, musique, animations et une ambiance qui change chaque semaine.</p><div className="actions"><a className="btn gold" href="#events">Voir les soirées →</a><a className="btn glass" href="#infos">Infos pratiques</a></div><div className="heroMeta"><div><b>Vendredi & samedi</b><small>18h — 01h</small></div><div><b>Place du Marché</b><small>Condé-en-Normandie</small></div></div></div><div className="live"><i/> ORIGINAL NIGHT BAR</div></section>
<section className="ticker"><div><span>ORIGINAL NIGHT BAR</span><i>✦</i><span>COCKTAILS</span><i>✦</i><span>DJ SETS</span><i>✦</i><span>SHOOTERS</span><i>✦</i><span>ANIMATIONS</span><i>✦</i><span>VIBREZ AUTREMENT</span><i>✦</i><span>ORIGINAL NIGHT BAR</span></div></section>
<section className="photoGrid"><article className="photo one"><div className="photoCopy"><span>LE BAR PREND VIE</span><strong>Du monde, du son<br/>et des lumières.</strong></div></article><article className="photo two"><div className="photoCopy"><span>AU COMPTOIR</span><strong>Une soirée<br/>commence par un verre.</strong></div></article></section>
<section className="section" id="experience"><div className="head"><div><span className="kicker">L’EXPÉRIENCE MAMBO</span><h2>La nuit a<br/><em>son adresse.</em></h2></div><p>LE MAMBO mélange bar de nuit, cocktails, animations et programmation musicale au cœur de Condé-en-Normandie. Le site reflète maintenant ce que l’on vient chercher : une vraie ambiance de sortie.</p></div><div className="cards"><article className="card image"><span className="mini">COCKTAILS & AMBIANCE</span><h3>Un comptoir vivant</h3><p>Des verres, des rencontres, des lumières et l’énergie d’un bar qui vit toute la soirée.</p></article><article className="card"><div className="icon">♫</div><span className="mini">MUSIQUE</span><h3>Chaque soirée change</h3><p>Rap, Shatta, années 80/90/2000, concepts estivaux et soirées à thème.</p></article><article className="card accent"><div className="icon">★</div><span className="mini">ANIMATIONS</span><h3>Plus qu’un bar</h3><p>Roue du Mambo, jeux, défis, lots et surprises au fil de la soirée.</p></article></div></section>
<section className="section events" id="events"><div className="head"><div><span className="kicker">AU PROGRAMME</span><h2>Ce week-end<br/><em>au Mambo.</em></h2></div><p>Deux soirées, deux ambiances. Les dernières annonces sont communiquées sur nos réseaux.</p></div><div className="eventGrid"><article className="event"><div className="eventTop"><span className="date"><b>07</b><small>AOÛT<br/>VEN.</small></span><span className="pill">ANIMATION · LOTS</span></div><div><h3>L’INFERNALE<br/>ROUE</h3><p>Une commande, une chance de jouer. Shooter, conso, cadeau, Banco… la roue décide.</p></div><div className="eventFoot"><span>18:00 — 01:00</span><a href="#infos">Infos →</a></div></article><article className="event featured"><div className="eventTop"><span className="date"><b>08</b><small>AOÛT<br/>SAM.</small></span><span className="pill">80’S · 90’S · 2000’S</span></div><div><h3>WE ARE<br/>THE KITSCH</h3><p>Les classiques qu’on connaît tous, les refrains qu’on assume et une soirée 100% nostalgie festive.</p></div><div className="eventFoot"><span>18:00 — 01:00</span><a href="#infos">Infos →</a></div></article></div></section>
<section className="mood"><div className="moodInner"><span className="kicker">ORIGINAL NIGHT BAR</span><blockquote>« Une soirée doit laisser un souvenir. »</blockquote><p>PLACE DU MARCHÉ · CONDÉ-EN-NORMANDIE</p></div></section>
<section className="section" id="infos"><div className="head"><div><span className="kicker">INFOS PRATIQUES</span><h2>On se retrouve<br/><em>au Mambo ?</em></h2></div></div><div className="infoGrid"><article className="info"><span className="mini">ADRESSE</span><h3>Place du Marché<br/>Condé-en-Normandie</h3><p>Au cœur du centre-ville.</p></article><article className="info"><span className="mini">HORAIRES</span><div className="hours"><div><span>Mardi — Jeudi</span><b>19h — 00h</b></div><div><span>Vendredi — Samedi</span><b>18h — 01h</b></div></div></article><article className="info goldInfo"><span className="mini">PROGRAMMATION</span><h3>Une nouvelle ambiance chaque semaine.</h3><p>Consulte les événements du moment avant de venir.</p></article></div></section>
<footer><div className="footbrand">LE MAMBO · ORIGINAL NIGHT BAR</div><div>PLACE DU MARCHÉ · CONDÉ-EN-NORMANDIE</div><div className="legal">L’abus d’alcool est dangereux pour la santé. À consommer avec modération. Vente d’alcool interdite aux mineurs.</div></footer>
<nav className="mobileNav"><a href="#top"><b>⌂</b><span>Accueil</span></a><a href="#events"><b>◫</b><span>Soirées</span></a><a href="#infos"><b>ⓘ</b><span>Infos</span></a></nav>
</main>}