const Arrow=()=> <span aria-hidden="true">→</span>;
export default function Home(){return <main>
<header className="top"><a className="brand" href="#top"><span className="miniLogo">LE<br/>M</span><span><strong>LE MAMBO</strong><small>ORIGINAL NIGHT BAR</small></span></a><nav><a href="#experience">Le Mambo</a><a href="#events">Événements</a><a href="#infos">Infos pratiques</a></nav><a className="cta" href="#events">Ce week-end <Arrow/></a></header>
<section className="hero" id="top"><div className="heroInner"><div className="artlogo"><span className="le">LE</span><span className="mambo">MAMBO</span><span className="subtitle">ORIGINAL NIGHT BAR</span></div><p>Place du Marché · Condé-en-Normandie<br/>Soirées, cocktails, animations et ambiance jusqu’au bout de la nuit.</p><div className="actions"><a className="btn gold" href="#events">Voir les soirées <Arrow/></a><a className="btn glass" href="#infos">Infos pratiques</a></div><div className="meta"><div><b>Vendredi & samedi</b><small>18h — 01h</small></div><div><b>Place du Marché</b><small>Condé-en-Normandie</small></div></div></div></section>
<section className="ticker"><div><span>ORIGINAL NIGHT BAR</span><i>✦</i><span>COCKTAILS</span><i>✦</i><span>DJ SETS</span><i>✦</i><span>SHOOTERS</span><i>✦</i><span>ANIMATIONS</span><i>✦</i><span>VIBREZ AUTREMENT</span><i>✦</i><span>ORIGINAL NIGHT BAR</span></div></section>
<section className="section" id="experience"><div className="head"><div><span className="kicker">L’EXPÉRIENCE MAMBO</span><h2>La nuit a<br/><em>son adresse.</em></h2></div><p>Un bar de nuit au cœur de Condé-en-Normandie, pensé comme un lieu vivant : une programmation qui change, des concepts maison et une ambiance reconnaissable.</p></div><div className="features"><article className="card"><div className="symbol">✦</div><small>AMBIANCE</small><h3>Une identité de nuit</h3><p>Noir, or, violet, rose et jeux de lumière : l’univers du Mambo se vit dès l’entrée.</p></article><article className="card"><div className="symbol">♫</div><small>MUSIQUE</small><h3>Chaque soirée change</h3><p>Rap, Shatta, années 80/90/2000, concepts estivaux et soirées à thème.</p></article><article className="card accent"><div className="symbol">★</div><small>ANIMATIONS</small><h3>Plus qu’un bar</h3><p>Roue du Mambo, jeux, défis, lots et surprises tout au long de la soirée.</p></article></div></section>
<section className="section events" id="events"><div className="head"><div><span className="kicker">AU PROGRAMME</span><h2>Ce week-end<br/><em>au Mambo.</em></h2></div><p>Deux soirées, deux ambiances. Retrouve les annonces et offres du moment directement sur nos réseaux.</p></div><div className="eventGrid"><article className="event"><div className="eventTop"><span className="date"><b>07</b><small>AOÛT<br/>VEN.</small></span><span className="pill">ANIMATION · LOTS</span></div><div><h3>L’INFERNALE<br/>ROUE</h3><p>Une commande, une chance de jouer. Shooter, conso, cadeau, Banco… la roue décide.</p></div><div className="eventFoot"><span>18:00 — 01:00</span><a href="#infos">Infos <Arrow/></a></div></article><article className="event featured"><div className="eventTop"><span className="date"><b>08</b><small>AOÛT<br/>SAM.</small></span><span className="pill">80’S · 90’S · 2000’S</span></div><div><h3>WE ARE<br/>THE KITSCH</h3><p>Les classiques qu’on connaît tous, les refrains qu’on assume et une soirée 100% nostalgie festive.</p></div><div className="eventFoot"><span>18:00 — 01:00</span><a href="#infos">Infos <Arrow/></a></div></article></div></section>
<section className="signature"><span className="kicker">ORIGINAL NIGHT BAR</span><blockquote>« Une soirée doit laisser un souvenir. »</blockquote><p>PLACE DU MARCHÉ · CONDÉ-EN-NORMANDIE</p></section>
<section className="section" id="infos"><div className="head"><div><span className="kicker">INFOS PRATIQUES</span><h2>On se retrouve<br/><em>au Mambo ?</em></h2></div></div><div className="infos"><article className="info"><span className="kicker">ADRESSE</span><h3>Place du Marché<br/>Condé-en-Normandie</h3><p>Au cœur du centre-ville.</p></article><article className="info"><span className="kicker">HORAIRES</span><div className="hours"><div><span>Mardi — Jeudi</span><b>19h — 00h</b></div><div><span>Vendredi — Samedi</span><b>18h — 01h</b></div></div></article><article className="info gold"><span className="kicker">PROGRAMMATION</span><h3>Une nouvelle ambiance chaque semaine.</h3><p>Consulte les événements du moment avant de venir.</p></article></div></section>
<footer><div className="footbrand">LE MAMBO · ORIGINAL NIGHT BAR</div><div>PLACE DU MARCHÉ · CONDÉ-EN-NORMANDIE</div><div className="legal">L’abus d’alcool est dangereux pour la santé. À consommer avec modération. Vente d’alcool interdite aux mineurs.</div></footer>
<nav className="mobileNav"><a href="#top"><b>⌂</b><span>Accueil</span></a><a href="#events"><b>◫</b><span>Soirées</span></a><a href="#infos"><b>ⓘ</b><span>Infos</span></a></nav>
</main>;}